name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker-build-and-push:
    name: Docker Build and Push
    uses: Apodini/.github/.github/workflows/docker-build-and-push.yml@v1
    with:
      image-name: valentinbootz/app-cloud-native-sustainability